baseURL: "/" # https://www.caiquecastro.com
languageCode: "en-us"
title: "Caique de Castro"
theme: "PaperMod"
copyright: "© 2021"

params:
  homeInfoParams:
    Title: Hi there
    Content: Senior Software Engineer

  socialIcons:
    - name: twitter
      url: https://twitter.com/caiquecastro_
    - name: github
      url: https://github.com/caiquecastro
    - name: gitlab
      url: https://gitlab.com/caiquecastro
    - name: linkedin
      url: https://www.linkedin.com/in/caiquecastro/
    - name: stackoverflow
      url: https://stackoverflow.com/users/2958728/caique-castro-soares-da-silva

  showPageTitleInTOC: false

markup:
  highlight:
    codeFences: false

  # Set to false to disallow raw HTML in markdown files
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "Home"
      title: "Home page"
      url: "/"
      weight: 1.0
    - name: About
      title: "About page"
      url: "/about/"
      weight: 2.0
    - name: "Uses"
      title: "My setup"
      url: "/uses/"
      weight: 3.0
    - name: "Blog"
      title: "Blog index"
      url: "/blog/"
      weight: 4.0

outputs:
  home:
    - HTML
    - RSS
    - JSON
